name: "\U0001F41B Bug Report"
description: Report an issue or possible bug
title: "\U0001F41B BUG:"
labels: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ##  Quick Checklist
        Thank you for taking the time to file a bug report! Please fill out this form as completely as possible.

        ✅ I am using the **latest version of the Astro Extension**.
  - type: textarea
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Describe the bug in steps that we can reproduce ourselves.
      value: |
        1. `npm init astro` using template <NAME>
        2. ...
        3. ...
        4. ...
        5. Error! Describe what went wrong (and what was expected instead)...
    validations:
      required: true
  - type: input
    attributes:
      label: Link to Minimal Reproducible Example
      description: |
        Provide a link to a minimal reproducible example. If the error only happens in one file, please specify in which file and where precisely does the error happen.
        If the file is in a private repository you can share a minimal version by copying the file's content in this issue, or using a service like [GitHub Gist](https://gist.github.com/) or [Pastebin](https://pastebin.com).
      placeholder: 'https://github.com/user/repo/blob/main/src/pages/index.astro'
    validations:
      required: true
