name: CI

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - '.vscode/**'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [18, 20]
        include:
          - os: windows-latest
            node_version: 18
          - os: macos-latest
            node_version: 18
      fail-fast: false

    name: 'Test: node-${{ matrix.node_version }}, ${{ matrix.os }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2

      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build the packages
        run: pnpm build

      - name: Test (Linux)
        run: xvfb-run -a pnpm test
        if: runner.os == 'Linux'

      - name: Test
        run: pnpm test
        if: runner.os != 'Linux'
