name: CI

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - '.vscode/**'
      - 'docs/**'
      - 'examples/**'
      - 'www/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [12, 14, 16]
      fail-fast: false

    name: 'Test: node-${{ matrix.node_version }}, ${{ matrix.os }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm 
        uses: pnpm/action-setup@v2.2.1

      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build the packages
        run: pnpm build

      - name: Test
        run: pnpm test
