name: Changelog

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Check out branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.1

      - name: Set up Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm install
        env:
          CI: true

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@master
        with:
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to VSCode Marketplace
        if: steps.changesets.outputs.published == 'true'
        working-directory: ./packages/vscode
        run: |
          sleep 5s
          npm i
          npm run build:ci:node
          npx vsce publish -p ${{ secrets.VSCE_TOKEN }} --target win32-x64 win32-ia32 win32-arm64 linux-x64 linux-arm64 linux-armhf darwin-x64 darwin-arm64 alpine-x64 alpine-arm64
          npm run build:ci:browser
          npx vsce publish -p ${{ secrets.VSCE_TOKEN }} --target web

      - name: Publish to OpenVSX
        if: steps.changesets.outputs.published == 'true'
        working-directory: ./packages/vscode
        run: |
          npm i
          npm run build:ci:node
          npx ovsx publish -p ${{ secrets.OVSX_TOKEN }} --target win32-x64 win32-ia32 win32-arm64 linux-x64 linux-arm64 linux-armhf darwin-x64 darwin-arm64 alpine-x64 alpine-arm64
          npm run build:ci:browser
          npx ovsx publish -p ${{ secrets.OVSX_TOKEN }} --target web

      - name: Send a Discord notification if a publish happens
        if: steps.changesets.outputs.published == 'true'
        id: discord-notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: 'A new release of the Astro VSCode extension just went out! [Release notes →](<https://github.com/withastro/language-tools/releases/>)'
